package pw.p1.introduccion;

import java.util.Date;


public class AnuncioMainProgram {

	public static void main(String[] args){
		
		/**
		 * exercise 4 - 1
		 */
		
		Tablon myTablon = new Tablon();

		
		/**
		 * exercise 4 - 2
		 */
		
		Anuncio anuncio = new Anuncio();
		Date fecha;
		
		// Announce 1
		
		anuncio.setTitulo("Titulo del primer anuncio");
		anuncio.setCuerpo("Este es el primer anuncio");
		anuncio.setUsuario("Pepe");
		
		try{ 
			fecha = new Date(System.currentTimeMillis());
			anuncio.setFecha(fecha);
		}catch(Exception e) {
			System.err.print("This is a generic exception generated by fecha...");
		}
		
		myTablon.publicarAnuncio(anuncio);
		
		
		// Announce 2
		
		anuncio.setTitulo("Titulo del segundo anuncio");
		anuncio.setCuerpo("Este es el segundo anuncio");
		anuncio.setUsuario("Paco");
		
		try{ 
			fecha = new Date(System.currentTimeMillis());
			anuncio.setFecha(fecha);
		}catch(Exception e) {
			System.err.print("This is a generic exception generated by fecha...");
		}
		
		myTablon.publicarAnuncio(anuncio);
		
		
		
		/**
		 * exercise 4 - 3
		 */
		
		myTablon.publicarAnuncio(new Anuncio("Auncio de Angel 1", "Cuerpor del Anuncio de Angel 1", "Angel"));
		myTablon.publicarAnuncio(new Anuncio("Auncio de Angel 2", "Cuerpor del Anuncio de Angel 2", "Angel"));
		
		
		/**
		 * exercise 4 - 4
		 */
		
	//	List<String> titulos = new ArrayList<String>();
		
	//	titulos = myTablon.verTitulos();
		
		
	}
}
